---
name: mypy checks

on:
  push: null
  pull_request: null

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mypy
        run: pip install -r requirements-dev.txt
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: "mypy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
